### ISSUE TITLE
nothing happens when selecting a .mov video on ios

### ISSUE THREAD

**Issue by hamdij0maa** [maitrungduc1410/react-native-video-trim#1]

**Comment by maitrungduc1410** [comment]
Is the event "onError" fired with some details?

Can you pass your video URL to isValidVideo to check if its can be editable?

**Comment by hamdij0maa** [comment]
it returns false always

**Comment by maitrungduc1410** [comment]
Can u send here the videoPath that you're passing to the component?

**Comment by maitrungduc1410** [comment]
And is it file selected from Photos?

Or a remote file?

**Comment by hamdij0maa** [comment]
selected from photos.      file:// ...... .MOV

**Comment by maitrungduc1410** [comment]
Okay I'll check this and get back to you

**Comment by maitrungduc1410** [comment]
@hamdij0maa which ios version are you using?

**Comment by hamdij0maa** [comment]
iOS 16.4

**Comment by maitrungduc1410** [comment]
@hamdij0maa sorry for not mentioning,

Are you using real device or Simulator?

on iOS you have to try on real device in order to work

**Comment by hamdij0maa** [comment]
Okay
