### ISSUE TITLE
Video format output

### ISSUE THREAD

**Issue by marcoss24** [maitrungduc1410/react-native-video-trim#11]
Hi, thank you for this library, it's great.

Is there any way we could specify the output format as currently on iOS when I input a mp4 file it would output a mov file.

**Comment by maitrungduc1410** [comment]
hi @marcoss24, in iOS, I'm using UIVideoController, which comes default by the platform, so the result in MOV is given by the platform.

So if you want to use different file format, you should take the returned output path and convert it to whatever format you want. The thing is during conversion you'll probably want to use different configurations, and it's overhead for this lib to support all of those usecases

**Comment by marcoss24** [comment]
> maitrungduc1410

Thank you for your prompt reply, I will follow your recommendations.
