### ISSUE TITLE
APK size is increased to 100 MB from 30 MB

### ISSUE THREAD

**Issue by vipulbuoyancy** [maitrungduc1410/react-native-video-trim#12]
Hi, 

Today I have added this package in to my application and after adding this package apk size has been increased to 100 MB. 

Please help me to reduce the size of the apk.

Thank you.

**Comment by vipulbuoyancy** [comment]
Hi @maitrungduc1410 , I have figured out that in the package we are getting the example & images as well, so by removing them I am able to reduce the size by around 15-16 MB, but I am still wondering why it is increased to 80 mb. 

It would be great if you can help me with other things which can increase the package size.

Thank you.

**Comment by noamanmansuri** [comment]
I think this guy is the culprit

repositories {
    ... other repos if any
    jcenter()
}

I am also trying to get rid out of this. Please drop a solution if you find anything.

**Comment by vipulbuoyancy** [comment]
Hi I found that ffmpeg is the culprit. It is eating more size. I am trying to figure out if we can just use the tool for cutting a video as we don't need any other feature for this.

@maitrungduc1410 , if you have any idea, please help us to reduce the size.

**Comment by maitrungduc1410** [comment]
Hi all thanks for your valuable info, I'll check and get back to you

**Comment by maitrungduc1410** [comment]
great to hear that :) @vipulbuoyancy

**Comment by pierroo** [comment]
@vipulbuoyancy can you share more about it?
Do you confirm that without the multiple architecture your end apk is around the same initial size? (30Mb)

can you also confirm the steps you took to disable multi architecture? That would be helpful :)

**Comment by taha200** [comment]
@vipulbuoyancy please let us know, grateful to you

**Comment by maitrungduc1410** [comment]
please upgrade to v1.0.9, 

default version is now FFMPEG "min" which gives smallest bundle size.

In case you need another version from FFMPEG Kit, Check my README.

 you can check for available versions from here: https://github.com/arthenica/ffmpeg-kit#9-packages
