### ISSUE TITLE
Issue with android-utils-sdk-1.1.2

### ISSUE THREAD

**Issue by AbdulMoeez060** [maitrungduc1410/react-native-video-trim#13]
Hi everyone,
I just added the react-native-video-trim to my project and it's giving the following error when i try to run on android,

   > Could not resolve com.github.iknow4:android-utils-sdk:1.1.2.
     Required by:
         project :app > project :react-native-video-trim
      > Could not resolve com.github.iknow4:android-utils-sdk:1.1.2.
         > Could not get resource 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'. Received status code 401 from server: Unauthorized

i am using the latest react native version 0.72.6

**Comment by maitrungduc1410** [comment]
Have you added jcenter to repositories in android/app/build.gradle?

**Comment by AbdulMoeez060** [comment]
I have added it to android/build.gradle as the repositories were there too, should i move these to the app folder.

**Comment by maitrungduc1410** [comment]
Yeah bro, pls follow my Readme and add it in correct file

**Comment by AbdulMoeez060** [comment]
Thanks a lot it works, i guess i ought to follow the setup guides properly.
