### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by AndyDesign999** [maitrungduc1410/react-native-video-trim#15]
After npm install react-native-video-trim, facing error in android platform.

```
repositories {
    ... other repos if any
    jcenter()
}
```
Error:
`Could not HEAD 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'. Received status code 401 from server: Unauthorized`

**Comment by wesleirocha13** [comment]
I'm having same problem.

Below is my `repositories` in `android/app/build.gradle`

```
repositories {
    google()
    mavenCentral()
    jcenter()
}
```

I made several types of changes regarding the `repositories` insertion and I always end up receiving this error

**Comment by maitrungduc1410** [comment]
Okay, I think I'll move the repo directly into my library to get rid of this error

**Comment by maitrungduc1410** [comment]
Hi guys, please upgrade to `1.0.5` this issue should be gone
