### ISSUE TITLE
WRITE_EXTERNAL_STORAGE permission was not requested

### ISSUE THREAD

**Issue by yanghun0070** [maitrungduc1410/react-native-video-trim#17]
After updating compileSdk and targetSdk to 33, a problem occurred where WRITE_EXTERNAL_STORAGE permission was not requested when installing the app.

**Comment by maitrungduc1410** [comment]
Thanks for letting me know,

Yeah from sdk 33 we don't need to request for storage permission, will push a fix soon

**Comment by maitrungduc1410** [comment]
please upgrade to 1.0.6, I fixed this, from Android >= 33, it won't request for this permission
