### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by hamdij0maa** [maitrungduc1410/react-native-video-trim#2]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.iknow4:android-utils-sdk:1.1.2.
     Required by:
         project :app > project :react-native-video-trim
      > Could not resolve com.github.iknow4:android-utils-sdk:1.1.2.
         > Could not get resource 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'. > Could not resolve com.github.iknow4:android-utils-sdk:1.1.2. Required by: project :app > project :react-native-video-trim > Could not resolve com.github.iknow4:android-utils-sdk:1.1.2. > Could not get resource 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'. > Could not HEAD 'https://www.jitpack.io/com/github/iknow4/android-utils-sdk/1.1.2/android-utils-sdk-1.1.2.pom'. Received status code 401 from server: Unauthorized * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 10s.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by maitrungduc1410** [comment]
I'll check this and get back to you soon

**Comment by maitrungduc1410** [comment]
Hi @hamdij0maa  found the issue, I forgot to mention in the README.

For Android, under `android/app/build.gradle`, add `jcenter` to `repositories` this:

```
repositories {
    ... other repos if any
    jcenter()
}
```
