### ISSUE TITLE
ios issue 

### ISSUE THREAD

**Issue by AnmolOyela** [maitrungduc1410/react-native-video-trim#22]
in ios i am not able to open editor please let me what to do

**Comment by maitrungduc1410** [comment]
Hi @AnmolOyela,

Please check if your video is valid using `isValidVideo`

Also try [my example](https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#usage) using https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#usage

**Comment by sn4f** [comment]
@AnmolOyela are you using an emulator?
