### ISSUE TITLE
Video size 360x640

### ISSUE THREAD

**Issue by sn4f** [maitrungduc1410/react-native-video-trim#25]
Hello, by default this package is resizing input video after trimming. Is it possible to change quality?
Currently all my output videos have 360x640px?

edit:
I tried without a trimmer and all is good. Example video https://streamable.com/rii125

**Comment by maitrungduc1410** [comment]
Hi, on iOS it's already set to High Quality: https://github.com/maitrungduc1410/react-native-video-trim/blob/master/ios/VideoTrim.swift#L57

And on my end I don't see this issue? Can you please check again?

**Comment by sn4f** [comment]
Hello, yes I tried all variants from their documentation and `typeIFrame1280x720` is the best for now but still video is blurred.

**Comment by sn4f** [comment]
To specify my issue, when trimming the video, it remains in perfect quality, but after the trimming, the output I receive is blurry. I've tried this with several different files and formats (mov, mp4).

**Comment by maitrungduc1410** [comment]
Hi,is it possible for you to provide some sample videos + respective generated outputs?

**Comment by sn4f** [comment]
> Hi,is it possible for you to provide some sample videos + respective generated outputs?

Of course, here is a record + output file
https://file.io/SaqW3VP3kUKx

**Comment by EuSet** [comment]
faced the same problem. quality is getting visibly worse after trimming

**Comment by maitrungduc1410** [comment]
Hi @EuSet  isue happens on ios right?

**Comment by sn4f** [comment]
If I may, it's only on iOS. Android looks good

**Comment by maitrungduc1410** [comment]
I think I need some rework on iOS instead of relying on UIVideoEditorController which is out of my control

**Comment by maitrungduc1410** [comment]
Hi @sn4f  @EuSet , please upgrade to `1.0.11`, remember to re-run `pod install`

iOS version is re-written from scratch, and the issue with video quality is solved

**Comment by EuSet** [comment]
Looks awesome!

**Comment by sn4f** [comment]
@maitrungduc1410 thank you so much for your quick help in this matter.
All the best.
