### ISSUE TITLE
Cache path is broken?

### ISSUE THREAD

**Issue by NicTorgersen** [maitrungduc1410/react-native-video-trim#28]
So I'm using this, perhaps a bit outside of the scope of the project. Videos are trimmed locally, there is no library management besides app cache. This test case was based on react-native for Android.

Using RNCamera to save a video, it gets saved to:  
`file:///data/user/0/com.my-app/cache/Camera/58fe498b-d334-4f55-8296-795e14c58363.mp4`

It works to pass this uri to `showEditor`, however the path from `onFinishTrimming` (outputPath) is  
`/data/user/0/com.my-app/files/trimmedVideo_1705855827.mp4`

I transform the path by adding `file://` like:  
`file:///data/user/0/com.my-app/files/trimmedVideo_1705855827.mp4`

But the video is "broken" according to the trimming library, perhaps the path is not available?

Necessary permissions are set in `AndroidManifest.xml` as well as `info.plist`

**Update:**

Seems like the videos produced are actually broken. They show up as 0B in the `Files`-explorer.

**Update:**

It works on real device, just not on emulator... Curious. Also noticed "trimming video..."-message does not show on emulator, but shows on device. Could the reason be that I'm on Apple Silicon?

**Comment by maitrungduc1410** [comment]
Hi,

I tested on Android emulator, it worked, but yeah, it'll better to always work with real device for both Android + iOS

About the "Trimming video..." text, please check the props `trimmingText` when you call `showEditor`. Check [here](https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#showeditorvideopath-string-config-editorconfig)

**Comment by NicTorgersen** [comment]
This works on device, not on emulator. Closing.
