### ISSUE TITLE
Is any plan that can set other version of FFMPEG-Kit for IOS like Android?

### ISSUE THREAD

**Issue by Parkjunwu** [maitrungduc1410/react-native-video-trim#30]
Is any plan that can set other version of FFMPEG-Kit for IOS like Android?
[Android set other version](https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#ffmpeg-version)
[ffmpeg-kit-ios](https://github.com/arthenica/ffmpeg-kit/tree/main/react-native#222-enabling-a-package-on-ios)
Thank you very much for making awesome library!

**Comment by maitrungduc1410** [comment]
For iOS I'm trying to find a way to do same as Android, will update you soon

**Comment by Parkjunwu** [comment]
> For iOS I'm trying to find a way to do same as Android, will update you soon

Thank you very much!

**Comment by Parkjunwu** [comment]
Wow Awesome! Thank you very much!
