### ISSUE TITLE
Not showing complete video in trimmer preview

### ISSUE THREAD

**Issue by ahmadhannan-ammag** [maitrungduc1410/react-native-video-trim#32]
on setting max duration in Android, its not showing the complete video in trimmer preview

 showEditor(`${path}`, {
      maxDuration: 300,
      trimmingText: 'Processing video...',
      saveToPhoto: false,
    });
    
 my sample video here

https://we.tl/t-o5FMRVwGyB

**Comment by maitrungduc1410** [comment]
I can't see your video, please upload it to somewhere else or simply drag here to github

**Comment by maitrungduc1410** [comment]
On Android the behaviour is slightly different, you can slide the range incase you set maxDuration

**Comment by ahmadhannan-ammag** [comment]
@maitrungduc1410 i on sliding range it doesn't show complete video. Like i uploaded folowing video, and gave maxDuration 300 seconds, it's showing only 5m 19 sec video, complete video duration was 5 min 53 seconds

screen shoot here

![image](https://github.com/maitrungduc1410/react-native-video-trim/assets/106084516/d1bfe9e3-70de-4b50-b30f-33aa9406f19f)


github not allowing me to upload 18 MBs video, so uploaded the input video on google drive. Link is here

https://drive.google.com/file/d/1nRR1d5mtNQKCvxnzmbfE50RkmhUHmQ9b/view?usp=sharing

**Comment by maitrungduc1410** [comment]
Let me check and get back to you

**Comment by ahmadhannan-ammag** [comment]
@maitrungduc1410 any update about this issue

**Comment by maitrungduc1410** [comment]
It's holiday in my country, please give sometime, probably end of this week I'll be back

**Comment by ahmadhannan-ammag** [comment]
@maitrungduc1410 I checked the latest version 1.0.16 , and tried with multiple videos, it's still having the same issue, For a long video on an Android complete video length not showing, on trimmer preview

**Comment by maitrungduc1410** [comment]
I'm checking it now, will back to you when I have new update

**Comment by ahmadhannan-ammag** [comment]
@maitrungduc1410 
Hi, did you get any time to check the issue?

**Comment by ahmadhannan-ammag** [comment]
@maitrungduc1410 Hi,  did you get any time to check the issue?

**Comment by maitrungduc1410** [comment]
> @maitrungduc1410 Hi, did you get any time to check the issue?

sorry @ahmadhannan-ammag  I don't have much capacity now, but I already put it in todo list

**Comment by maitrungduc1410** [comment]
hi @ahmadhannan-ammag , please upgrade to v2, Android UI is completely revamped, sync with iOS

**Comment by benjamin-luupli** [comment]
how do i take away the extra 0.00 on the duration for the trimmer?
my duration shows like this 1:30.000  but I want the digit to be just 1:30 is there a way to edit this view?

**Comment by maitrungduc1410** [comment]
I'll add support for timing format

**Comment by benjamin-luupli** [comment]
That would be great and also ability to add headers on top to the editor
view seems not to even position any thing on it

**Comment by maitrungduc1410** [comment]
Good suggestion, I'll put in todo list

**Comment by benjamin-luupli** [comment]
A quick follow up I want to first take the entire video length and trim. So
if I trim to a duration of 30 and that the duration I want and the user
exceeds 30 Im showing a pop up alert that duration has exceeded 30 but here
the onTrimming finish even has been fired and the trimming modal get stuck
how do I close that modal that says trimming video wen the user exceeds my
set duration?
