### ISSUE TITLE
do we have some options to seek timeline like in android on ios

### ISSUE THREAD

**Issue by JavoxirNazarov** [maitrungduc1410/react-native-video-trim#33]
in android we can seek timeline but on ios we can't.  can we have such option for ios. or could you suggest any way to patch librarry

**Comment by maitrungduc1410** [comment]
this is pending item I haven't yet finished.

you can fork and update your own, but you need to understand native code (Swift/Java)

**Comment by maitrungduc1410** [comment]
please upgrade to latest version (1.0.22) and try again

**Comment by maitrungduc1410** [comment]
hey, pls upgrade to v2, Android UI is completely revamped, synced with iOS
