### ISSUE TITLE
Does it work with Expo

### ISSUE THREAD

**Issue by Stancobridge** [maitrungduc1410/react-native-video-trim#34]
I want to use this package with Expo, using a custom-build dev client.

I want to know if this package will work with expo, if I rebuild, do I also need to add the react-native-video-trim in the plugins property

**Comment by maitrungduc1410** [comment]
I'm working in expo support and will release soon

**Comment by maitrungduc1410** [comment]
Hi @Stancobridge yes it does work with Expo.

Just remember to run `npx expo prebuild` if you haven't done so, this is for native code to take effect (still follow **managed workflow**, [detail](https://docs.expo.dev/workflow/prebuild/))

**Comment by PrinceUBS** [comment]
i'm also facing the same issue. even running below 2 commands.

`bunx expo prebuild`
&
`bunx pod-install`

<img width="948" alt="Screenshot 2024-08-14 at 4 19 50 PM" src="https://github.com/user-attachments/assets/5b1ac045-da16-4f15-b0a1-cd6ff0aec9cc">

**Comment by maitrungduc1410** [comment]
As the error saying, you have naming conflicts, please check again

**Comment by PrinceUBS** [comment]
Ya correct @maitrungduc1410, thanks bro!
