### ISSUE TITLE
[Feature Request | Bug] Ensure Video File Readiness Within `showEditor()` Before Saving

### ISSUE THREAD

**Issue by anonymousDog12** [maitrungduc1410/react-native-video-trim#36]
Greetings~ 

## Issue Description

- When invoking `showEditor()`, if I press the **save** button immediately after the editor opens, then the trimmed video often turns out to be corrupted
- Conversely, if I allow some time to elapse before pressing save, the video is trimmed correctly without any issues.

## Potential Cause and Suggested Solution

- I am guessing the corruption is caused by **attempting to save / start trimming videos before the original videos are fully loaded**, but the UI lacks indicators to show if the file is ready.
- So would it be possible to implement a check, or a "loading icon" to ensure file is fully loaded, before user can save and trim can happen? 

Thank you for investigating the issue and considering this suggestion! 

---

P.S. this is the video file I used for testing. 

https://github.com/maitrungduc1410/react-native-video-trim/assets/27938057/96e2b4d1-3126-4d16-959f-b41a26d7db98

**Comment by maitrungduc1410** [comment]
Great suggestion, I'll add this in next release. 

Thank you 🙏

**Comment by anonymousDog12** [comment]
Thank you for your updates, @maitrungduc1410 🙏
