### ISSUE TITLE
getting Reference to property 'player' in closure requires explicit use of 'self' to make capture semantics explicit

### ISSUE THREAD

**Issue by amosaxe** [maitrungduc1410/react-native-video-trim#37]
While running in ios, we are getting the following error:/Users/prachhhi/Documents/yes/app/AppV2/node_modules/react-native-video-trim/ios/VideoTrimmerViewController.swift:254:16 Reference to property 'player' in closure requires explicit use of 'self' to make capture semantics explicit
![Screenshot 2024-02-14 at 8 48 28 PM](https://github.com/maitrungduc1410/react-native-video-trim/assets/122282992/06726cd9-53c3-4dc3-8cbc-1b863998bde9)

**Comment by maitrungduc1410** [comment]
which version of this library and RN are you using?

Have you run Pod install? can you try this in new project, because with the above errors I'll definitely will see it and never publish :)

**Comment by amosaxe** [comment]
RN version: 0.72.4
react-native-video-trim version: 1.0.10

yes we have ran pod install.

Yes correct and apologies for not adding full context, the same code is running  in another system so we suspect something wrong with xcode settings. But as this issue is coming with library only, I thought of asking for help here.

**Comment by maitrungduc1410** [comment]
Can you click each of the error then screenshot and show me exact location for each error?

**Comment by amosaxe** [comment]
This file contains all the errors
![Screenshot 2024-02-14 at 10 33 19 PM](https://github.com/maitrungduc1410/react-native-video-trim/assets/122282992/808fb8ba-40de-42f6-9663-02ffbe48319e)

**Comment by maitrungduc1410** [comment]
Let me push a fix for this, I think this is about backward compatibility, it's really fine on my end

**Comment by amosaxe** [comment]
Sure, thanks a lot, yes I am also able to run on another system with latest xcode so looks like that only.

**Comment by amosaxe** [comment]
Hey @maitrungduc1410, Yep this worked, thanks for this, now I am thinking why I didnt just patched on my own and raised a PR lol. 
Again thanks for quickly responding and helping.
