### ISSUE TITLE
Event returns 'Command failed with state COMPLETED and rc 1.null' when i finish trim

### ISSUE THREAD

**Issue by mguerrero-exe** [maitrungduc1410/react-native-video-trim#38]
I got this error in the logs when I try to trim a video, and Idk what happens, im using 'react-native-image-cropp-picker', and making sure the file is valid before trimming the video, but when I finish the trim, the editor just returns an error in the console:

```js
{ 
  name: 'onError',
  message: 'Command failed with state COMPLETED and rc 1.null'
 }
 ```

Here I make sure the video is valid
```jsx
if (type === 'video') {
  isValidVideo((filesFromPicker as ImageOrVideo).path).then((e) => console.log(e))
    showEditor((filesFromPicker as ImageOrVideo).path, {
    maxDuration: 30,
    saveToPhoto: false,
    enableSaveDialog: false
   })
}
```

Events:
```jsx
useEffect(() => {
  const eventEmitter = new NativeEventEmitter(NativeModules.VideoTrim);

  const subscription = eventEmitter.addListener('VideoTrim', (e) => {
    switch (e.name) {
      case 'onShow': {
        console.log('onShowListener', e);
        break;
      }
      case 'onHide': {
        console.log('onHide', e);
        break;
      }
      case 'onStartTrimming': {
        console.log('onStartTrimming', e);
        break;
      }
      case 'onFinishTrimming': {
        console.log('onFinishTrimming', e);
        break;
      }
      case 'onCancelTrimming': {
        console.log('onCancelTrimming', e);
        break;
      }
      case 'onError': {
        console.log('onError', e);
        break;
      }
    }
  })
 return () => {
    subscription.remove()
  }
}, [])
```

It should be noted that I am not using any other library that could affect its functionality, I do not use any FFMPEG kit either, so the one that comes with the default trimmer library is the one that is in use.

**Comment by maitrungduc1410** [comment]
Are you using real device?

If not, pls always use real device for that

**Comment by mguerrero-exe** [comment]
No, I'm using an emulator, I thought using real devices was only necessary for IOS, and I'm testing on an Android device, but I'll test on a real device...

**Comment by maitrungduc1410** [comment]
I'm gonna update the README and clearly mention this, it's required to run in real device for both Android and iOS

**Comment by mguerrero-exe** [comment]
Solved!!!
Thanks you!

**Comment by maitrungduc1410** [comment]
IsValidVideo is baes on platform function to check if a file is actual video, you can check in native code, it's simple logics

**Comment by maitrungduc1410** [comment]
Btw, is it possible for you to provide the input video you're using to test, I'll try to reproduce from my end

**Comment by chetanbhadarka** [comment]
> Btw, is it possible for you to provide the input video you're using to test, I'll try to reproduce from my end

I'm using [react-native-multiple-image-picker](https://github.com/baronha/react-native-multiple-image-picker) for pick video from internal storage of device.

here is [Response object](https://github.com/baronha/react-native-multiple-image-picker?tab=readme-ov-file#response-object).

I checked with "path" first and then with "realPath" as I'm testing on android device so. In "IsValidVideo" function for both I'm getting "true" but when Proceed after trimming video getting error.

**Comment by maitrungduc1410** [comment]
You're testing on android right?

And it's from internal store?

**Comment by chetanbhadarka** [comment]
> You're testing on android right?
> 
> What do you mean by internal store?
> 
> Can you try move it to Photos and try again?

Yes in android. Internal storage means I'm not using any SD card. But i'll try it with recorded video from Camera and let you update here.

**Comment by chetanbhadarka** [comment]
@maitrungduc1410, I've tested with recorded video from Camera and it return "onFinishTrimming". it mean trim works.

but why not working for other path. I have a video in download folder (downloaded from browser, so) but getting error after trim proceed. can you please suggest me how to figure out this thing.

**Comment by maitrungduc1410** [comment]
@chetanbhadarka 

I'm trying on Android 9, API 28, anything I select in Gallary App works. In the app I also try with Downloads folder which contains downloaded video from browser

**Comment by chetanbhadarka** [comment]
> @chetanbhadarka
> 
> I'm trying on Android 9, API 28, anything I select in Gallary App works. In the app I also try with Downloads folder which contains downloaded video from browser

Okay, I have Android 11, API 30.

Well thank you for your support, I'll test  with other file provider and let you know.

**Comment by maitrungduc1410** [comment]
hi guys, this issue may caused by having space in input file name. Please upgrade to latest version, I fixed it

**Comment by maitrungduc1410** [comment]
if you need more info about this error, please check my comment here: https://github.com/maitrungduc1410/react-native-video-trim/issues/111#issuecomment-3303456631
