### ISSUE TITLE
Black screen on trimming and enquiry for min duration

### ISSUE THREAD

**Issue by amosaxe** [maitrungduc1410/react-native-video-trim#39]
For some videos, if it is trimmed from the beginning to length 3sec(min), then the video contains only black frames(fully) but the voice plays.

There is no option to set min duration limit(default is 3 secs but if I use video with length less then 3secs then the trimmer gives error that video shorter than 3sec, can't proceed)

version: latest(1.0.16)
device : android (multiple versions) , both of the issues are not there in iOS

**Comment by maitrungduc1410** [comment]
is it possible for you to provide your input video for me to test?

also provide your code

**Comment by amosaxe** [comment]
Sure, here it is https://drive.google.com/file/d/1xC-irLvaRgOA174TzSp2ujZFTUcMj8DD/view?usp=sharing

Code: 
```
const handleTrim = async () => {
        if (selectedMediaObj) {
            setIsLoading(true);
            await showEditor(selectedMediaObj?.uri, {
                maxDuration: maxAllowedVideoLength,
                saveToPhoto: false,
            });
        }
    };
```


```
useEffect(() => {
        const eventEmitter = new NativeEventEmitter(NativeModules.VideoTrim);
        const subscription = eventEmitter.addListener(
            'VideoTrim',
            async event => {
                switch (event.name) {
                    case 'onShow': {
                        break;
                    }
                    case 'onHide': {
                        break;
                    }
                    case 'onStartTrimming': {
                        break;
                    }
                    case 'onFinishTrimming': {
                        if (mediaObj?.uri) {
                            const obj = { ...mediaObj };
                            obj.uri = `file://${event?.outputPath}`;
                            setMediaObj(obj);

                            setIsLoading(false);
                        } else {
                            onClose();
                        }

                        break;
                    }
                    case 'onCancelTrimming': {
                        setIsLoading(false);
                        break;
                    }
                    case 'onError': {
                        onClose();
                        break;
                    }
                }
            },
        );

        return () => {
            subscription.remove();
        };
    }, [mediaObj]);
```

**Comment by maitrungduc1410** [comment]
@amosaxe can I confirm that your issue happened on Android only.

iOS works fine?

**Comment by amosaxe** [comment]
yes iOS works fine.

**Comment by maitrungduc1410** [comment]
Hi, I'm trying to reproduce your issue but it's working fine, video saved to Gallery (Photos) with video + audio

**Comment by amosaxe** [comment]
Yes it is getting saved but using react-native-video player the video frames remains blank….can it be react-native-video issue, or anything else you are aware of?

**Comment by maitrungduc1410** [comment]
yes, high chance. 

You can do this to test: 
- do trimming again with same video
- open the output video in rn-video-trim, it uses VideoView on Android, if it shows okay then I think no issue at all :)

**Comment by maitrungduc1410** [comment]
btw, pls upgrade to `1.0.17`, I added support for `minDuration`

**Comment by amosaxe** [comment]
Hmm, I tried out the steps as you mentioned, that works. The issue occurs only with those video that are trimmed to 3 second, also that too not with all videos, will look in RN-video side. Thanks

Thanks for the update and support for `minDuration`, but after the update it comes like below (with or without the usage of the minDuration prop), seems like its a bug.
<img width="681" alt="Screenshot 2024-03-02 at 2 06 30 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/122282992/481b6a77-9fe4-4d84-9aaa-b11569621d67">

**Comment by amosaxe** [comment]
Hi @maitrungduc1410 , can you help with this?

**Comment by maitrungduc1410** [comment]
> Hmm, I tried out the steps as you mentioned, that works. The issue occurs only with those video that are trimmed to 3 second, also that too not with all videos, will look in RN-video side. Thanks

> Thanks for the update and support for minDuration, but after the update it comes like below (with or without the usage of the minDuration prop, i tried with minDuration > 0), seems like its a bug.

for this issue, what's your code + input video can I get?

**Comment by maitrungduc1410** [comment]
hi @amosaxe pls upgrade to v2, Android UI is completely revamped, synced with iOS

**Comment by amosaxe** [comment]
Hi @maitrungduc1410, thanks for the update and apologies for not reverting last time, had missed this. Will check it out today. Kudos!
