### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "ffmpeg-kit-ios-min"

### ISSUE THREAD

**Issue by mguerrero-exe** [maitrungduc1410/react-native-video-trim#40]
I got this error in IOS when try to install pods:
```
[!] CocoaPods could not find compatible versions for pod "ffmpeg-kit-ios-min":
  In Podfile:
    react-native-video-trim (from ../node_modules/react-native-video-trim) was resolved to 1.0.16, which depends on
      ffmpeg-kit-ios-min (~> 6.0)

Specs satisfying the ffmpeg-kit-ios-min (~> 6.0) dependency were found, but they required a higher minimum deployment target.
```

I don't use any FFMPEG kit, so the one that comes with the default trimmer library is the one that is in use.

**Comment by maitrungduc1410** [comment]
it supports iOS 12.1 or later, please update your deployment target

**Comment by mguerrero-exe** [comment]
My deployment target is 12.4

**Comment by maitrungduc1410** [comment]
make sure you have set it all required places: 

<img width="881" alt="Screenshot 2024-03-01 at 9 47 32 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/16630193/4af7fbf1-a46c-4443-b923-0c559cec2392">
<img width="835" alt="Screenshot 2024-03-01 at 9 47 15 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/16630193/b5ddb828-bfe9-4931-a0e7-a18056a0e602">

**Comment by c-info** [comment]
The 'Pods-demo_app' target has frameworks with conflicting names: ffmpegkit.xcframework, libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.

when using ffmpeg-kit-react-native

**Comment by maitrungduc1410** [comment]
@c-info I'll check this and get back to you

**Comment by maitrungduc1410** [comment]
Hi guys, according to [ffmpegkit-react-native](https://github.com/arthenica/ffmpeg-kit/blob/main/react-native/ffmpeg-kit-react-native.podspec), for iOS it's using ffmpegkit-https, version = 6.0

Therefore when running pod install you need to do this (setting 2 extras ENV):
```
FFMPEGKIT_PACKAGE=https FFMPEGKIT_PACKAGE_VERSION=6.0 pod install
```

**Comment by ymhmd** [comment]
I'm facing the same issue, any clue how to fix it? 

Thanks!

**Comment by maitrungduc1410** [comment]
> I'm facing the same issue, any clue how to fix it?
> 
> Thanks!

hi, can you try update your Deployment Target?

**Comment by benjamin-luupli** [comment]
Hi package builds alright on my ios device when I do pod install with the command you gave 
FFMPEGKIT_PACKAGE=https FFMPEGKIT_PACKAGE_VERSION=6.0 pod install
but on app center when I'm trying to build for production I get this error 
[!] The 'Pods-app' target has frameworks with conflicting names: ffmpegkit.xcframework, libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.

is there any suggestion to by-pass this in my production environment in appcenter?

**Comment by maitrungduc1410** [comment]
Added instruction how to solve this issue in [README](https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#naming-conflict-with-ffmpeg-kit-react-native)

**Comment by LianVyv** [comment]
Anyone also getting stuck on readme for iOS this worked for me

`FFMPEGKIT_PACKAGE=https pod install `

**Comment by LianVyv** [comment]
@maitrungduc1410 I want to use full-gpl which works fine on Android for me. 

But on iOS i'm struggling with this compatible version issue as I understand your README it says I just need to run add set my package to full-gpl and then set the version and it says it is version 6.0 so technically I don't need to set it as you already have it on default but I have set it to see if it will solve my issue but it didn't. 

Could you maybe tell me what I'm doing wrong?

Deployment target is set to 13.4

This is my final code I was running

```FFMPEGKIT_PACKAGE=full-gpl FFMPEGKIT_PACKAGE_VERSION=6.0 pod install ```

Then my error
```
Installing ffmpeg-kit-ios-full-gpl (6.0)
Installing react-native-video-trim 2.2.1
[!] The 'Pods-myapp' target has frameworks with conflicting names: ffmpegkit.xcframework, libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.
```

**Comment by LianVyv** [comment]
@maitrungduc1410 I now understood my issue after looking at what they did https://www.npmjs.com/package/ffmpeg-kit-react-native all I needed was to also add the version I wanted to my podfile. 

I have improved the message for iOS incase others get confused with the PR: https://github.com/maitrungduc1410/react-native-video-trim/pull/68
