### ISSUE TITLE
Audio only support

### ISSUE THREAD

**Issue by nguyen95** [maitrungduc1410/react-native-video-trim#41]
Does this library support cutting audio files? Or are there plans for this in the future?

**Comment by maitrungduc1410** [comment]
this lib is using FFMPEG so of course audio trimming is possible.

I tended to build this for video, but your idea is truely valid, I'll put this in roadmap and develop soon

**Comment by nguyen95** [comment]
Thanks, I'm looking forward to it!

**Comment by maitrungduc1410** [comment]
hi @terence1990 @nguyen95 
- audio only is now supported
- local and remote files also supported
please upgrade to `^2.1.0`

**Comment by terence1990** [comment]
@maitrungduc1410 awesome, remote files is an absolute game changer!

**Comment by nguyen95** [comment]
The output file is in mp4 format, I think mp3 would be more convenient

**Comment by maitrungduc1410** [comment]
@nguyen95 you can customize it using "outputExt". Please check Readme
