### ISSUE TITLE
File is not a valid video in iOS even select mp4 files

### ISSUE THREAD

**Issue by Etaliya** [maitrungduc1410/react-native-video-trim#42]

**Comment by maitrungduc1410** [comment]
are you using simulator?

note that it only works on real device

is it possible for you to provide your sample video?

**Comment by Etaliya** [comment]
> are you using simulator?
> 
> note that it only works on real device
> 
> is it possible for you to provide your sample video?


https://github.com/maitrungduc1410/react-native-video-trim/assets/54949248/ee28d4d1-0d99-42ea-8c91-ec54b29167f3

**Comment by maitrungduc1410** [comment]
note that you have to use real device. Simulator/Emulator won't work

**Comment by maitrungduc1410** [comment]
Your video is fine

![image](https://github.com/maitrungduc1410/react-native-video-trim/assets/16630193/673b319b-d45e-4e84-a145-7b1ced720461)

**Comment by Etaliya** [comment]
> note that you have to use real device. Simulator/Emulator won't work

It's work in real device not a Simulator.
