### ISSUE TITLE
Video Position Not Changing When Swiping Left and Right in iOS

### ISSUE THREAD

**Issue by shiyansiva** [maitrungduc1410/react-native-video-trim#44]
@maitrungduc1410  when I swipe left and right in the video player swiper, the position of the video does not change accordingly. Any suggestions or solutions would be greatly appreciated.

https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/fd121a1f-3be0-43b8-9a12-4409d1d075f7

**Comment by maitrungduc1410** [comment]
@shiyansiva  I'm not clear which part is incorrect,

**Comment by shiyansiva** [comment]
> @shiyansiva I'm not clear which part is incorrect,

@maitrungduc1410 Can you see my video? Even after I moved the left and right sliders, the video position did not change.

**Comment by maitrungduc1410** [comment]
yes this one is not yet implemented, I'll put it in road map and develop

**Comment by shiyansiva** [comment]
> yes this one is not yet implemented, I'll put it in road map and develop

Okay, Thanks @maitrungduc1410

**Comment by maitrungduc1410** [comment]
@shiyansiva please upgrade to latest version (1.0.22) this feature is released

**Comment by shiyansiva** [comment]
> @shiyansiva please upgrade to latest version (1.0.22) this feature is released

Thanks @maitrungduc1410
