### ISSUE TITLE
Android 14 listener not working

### ISSUE THREAD

**Issue by zocial-rajesh** [maitrungduc1410/react-native-video-trim#45]
componentDidMount() {
   const eventEmitter = new NativeEventEmitter(NativeModules.VideoTrim);
   this.subscription = eventEmitter.addListener('VideoTrim', this.handleEvent);
}

handleEvent = (event) => {
    switch (event.name) {
      case 'onShow': {
        console.log('onShowListener', event);
        break;
      }
      case 'onHide': {
        console.log('onHide', event);
        break;
      }
      case 'onStartTrimming': {
        console.log('onStartTrimming', event);
        break;
      }
      case 'onFinishTrimming': {
        console.log('onFinishTrimming', event);
        break;
      }
      case 'onCancelTrimming': {
        console.log('onCancelTrimming', event);
        break;
      }
      case 'onError': {
        console.log('onError', event);
        break;
      }
    }
  }

handleEvent is not called
React Native 0.64.2
Tested in real device

**Comment by zocial-rajesh** [comment]
https://github.com/maitrungduc1410/react-native-video-trim/blob/9c36ed1b32ec57021065bbf3d4d0b82592b15940/android/src/main/java/com/videotrim/VideoTrimModule.java#L305

Removed if condition. it works well! 
I think listener count is not required.

**Comment by maitrungduc1410** [comment]
Thanks for letting me know, maybe it's about RN version, yours is old. But I'll do a check on my end on this
