### ISSUE TITLE
Android Build Issue

### ISSUE THREAD

**Issue by Sivakumar415** [maitrungduc1410/react-native-video-trim#5]
I encountered an issue while building my Android project. The build process is failing with an error message.

**Expected Behavior:**
The build process should complete without errors, generating the debug APK.

**Actual Behavior:**
The build process fails with the following error message:

_Execution failed for task ':app:compileReleaseJavaWithJavac'.
Compilation failed; see the compiler error output for details.

Task :app:compileReleaseJavaWithJavac FAILED

android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:65: error: package undefined does not exist
import undefined.VideoTrimPackage;
                ^
android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:138: error: cannot find symbol
      new VideoTrimPackage(),
          ^
  symbol:   class VideoTrimPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception._

**Additional Information:**
"react": "16.13.1"
"react-native": "~0.63.4",
 "react-native-video-trim": "^1.0.2",

For Android:
 ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = '1.3.41'
    }
    repositories {
        google()
        jcenter()
    }

**Comment by maitrungduc1410** [comment]
thanks for reporting this issue, I'll push an update for this soon

**Comment by maitrungduc1410** [comment]
Hi please upgrade to version 1.0.3 and try again
