### ISSUE TITLE
Target has frameworks with conflicting names

### ISSUE THREAD

**Issue by anup-a** [maitrungduc1410/react-native-video-trim#52]
I'm using expo for my project.

And while running - `npx expo prebuild`

I encouter this error 
```
✔ Cleared ios code
✔ Created native directory
› Using current versions instead of recommended react-native@0.73.6.
✔ Updated package.json | no changes
» ios: scheme: "ios.infoPlist.CFBundleURLTypes" is set in the config. Ignoring abstract property "scheme": aivideo
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: The 'Pods-XXXX' target has frameworks with conflicting names: ffmpegkit.xcframework, libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.

pod install --repo-update --ansi exited with non-zero code: 1
```

I'm using ffmpeg-kit separately in my app for other tasks, could that have caused the conflict ?

```js
    // app.json
      [
        "@config-plugins/ffmpeg-kit-react-native",
        {
          package: "full-gpl",
        },
      ]
    
```

I saw in the readme that there is a way to update the ffmpeg version, so if I make it same as what I have pre-installed, will that resolve the issue ?

Also is there any way to do the same in expo ? (rather than updating android and ios buildscripts individually)

Thanks

**Comment by maitrungduc1410** [comment]
> I saw in the readme that there is a way to update the ffmpeg version, so if I make it same as what I have pre-installed, will that resolve the issue ?

yes

> Also is there any way to do the same in expo ? (rather than updating android and ios buildscripts individually)

pardon? what you're doing above is correct already :), you just need to find out correct version to use. Check this issue I found it for you: https://github.com/maitrungduc1410/react-native-video-trim/issues/40

**Comment by Energieman** [comment]
In my case, I uninstalled the 'react-native-audio-api' and it worked
