### ISSUE TITLE
Getting error while install the pod

### ISSUE THREAD

**Issue by sw-tt-ankitborad** [maitrungduc1410/react-native-video-trim#53]
[!] The following Swift pods cannot yet be integrated as static libraries:
 
The Swift pod `react-native-video-trim` depends upon `glog`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by maitrungduc1410** [comment]
pls check this: https://github.com/expo/expo/issues/25905

Summary: 
removing node_modules, Pods, then reinstall everything

**Comment by sw-tt-ankitborad** [comment]
@maitrungduc1410, thank you for the quick assistance.
We've reviewed the suggestions provided but are still encountering the same error.

Just so you know, we're utilizing React Native CLI.

**Comment by maitrungduc1410** [comment]
@sw-tt-ankitborad on which version of RN are you using? which platform are you?

maybe you try
- delete Pods folder under ios, then rerun pod install
- restart your machine/terminal

**Comment by sw-tt-ankitborad** [comment]
- We're currently utilizing React Native version 0.73.6, and facing issue in iOS platform.

- We've attempted the steps you provided, but we're still encountering the same version.

**Comment by maitrungduc1410** [comment]
can you try generate new project and install this package to see if you can reproduce?

**Comment by sw-tt-ankitborad** [comment]
We'll take a look and inform you.
