### ISSUE TITLE
packege ffmpeg-kit-ios-min conflict with ffmpeg-kit-react-native

### ISSUE THREAD

**Issue by sunliangabc** [maitrungduc1410/react-native-video-trim#54]
Installing both ffmpeg-kit-react-native and react-native-video-trim, then run npx pod-install, there an error reporting conflicts:

![image](https://github.com/maitrungduc1410/react-native-video-trim/assets/23044818/7f24631f-2fc4-4d9c-a284-4ae9e901885b)

**Comment by maitrungduc1410** [comment]
pls check: https://github.com/maitrungduc1410/react-native-video-trim/issues/52
