### ISSUE TITLE
[Question] Initialize trimmer with a specific start and end time ?

### ISSUE THREAD

**Issue by jon301** [maitrungduc1410/react-native-video-trim#57]
Hi @maitrungduc1410 👋

Thanks for your work on this library 🙏 I had a question regarding the trimmer
Is it possible to open the video editor but with a specific start and end time for the trimmer ?

Thanks!

**Comment by maitrungduc1410** [comment]
I thought about this long back ago, but consider this is video trimmer and referencing to other trimmers like native iOS/Android (provided by OS), this startTime/endTime looks not relevant to a video trimmer, that's why I haven't planned to work on it yet

**Comment by jon301** [comment]
Sounds good, thanks!🙏
