### ISSUE TITLE
Video trimmer is not movable.

### ISSUE THREAD

**Issue by DevModi987** [maitrungduc1410/react-native-video-trim#58]
Hello, Your Package is awsome and it is very useful. 
But there is no option for video trimmer to move on video timeline like whatsapp. and also there is no option available to change trimmer color.

**Comment by maitrungduc1410** [comment]
> But there is no option for video trimmer to move on video timeline like whatsapp

I did have this in Android before, but then I found that it's not good in UX (let say user imports a long video file and have to scroll all the way to the right to find correct part to trim)

Then learn from what giants do (ios/android), you can try doing trim from Gallery/Photos app, that's what I'm following :)

**Comment by maitrungduc1410** [comment]
> there is no option available to change trimmer color.

I'll add support for this

**Comment by DevModi987** [comment]
Thank You For Your Response.
Actually in my case there is a limit of video trim i.e 30 seconds so i have to put maxDuration = 30 but in this case it is difficult to move trimmer to that particular point that i actually want to trim. 
if you will help in this case than it will be a great for help for me.

**Comment by DevModi987** [comment]
Thank You For Your Response.
Actually in my case there is a limit of video trim i.e 30 seconds so i have to put maxDuration = 30 but in this case it is difficult to move trimmer to that particular point that i actually want to trim.
if you will help in this case than it will be a great help for me.
