### ISSUE TITLE
Default ffmpeg-kit version should be a stable version.

### ISSUE THREAD

**Issue by dipo1** [maitrungduc1410/react-native-video-trim#61]
I'll suggest using a stable (LTS) version of `ffmpeg-kit` as default. The current default is 6.0-2 requires a `minSdkVersion` >= 24 which is greater than React Native's current `minSdkVersion` (23).

According to this [article](https://www.nearform.com/insights/adding-react-native-to-a-complex-app-part-3-android/), having a `minSdkVersion` greater than React Native's default may cause some issues.

In my case, it was causing an error `java.lang.UnsatisfiedLinkError - dlopen failed: library "libhermes.so" not found in MainActivity.onCreate` on a device running Android 12 when I try to use some libraries expected to be available in latest React Native version.

Setting ffmpeg-kit version to 6.0-2.LTS resolved the issue.

**Comment by maitrungduc1410** [comment]
You can check the readme , you can fully customize ffmpegkit version, sdk version for this lib. 

Keep thing simple, else I'll need to update this lib everytime Rn update their min sdk version
