### ISSUE TITLE
Video Compression on Trim Video.

### ISSUE THREAD

**Issue by DevModi987** [maitrungduc1410/react-native-video-trim#62]
is there any option available that apply video compression method after video trim?

**Comment by maitrungduc1410** [comment]
Not for now, but I'll add support for this in the future

**Comment by maitrungduc1410** [comment]
hi, for this, for the sake of simplicity this lib focuses on trimming operations only, and I'm using "-c copy", this means that the video and audio data will be copied as-is, with no compression applied
