### ISSUE TITLE
Controlling video trimming progress and play button

### ISSUE THREAD

**Issue by benjamin-luupli** [maitrungduc1410/react-native-video-trim#63]
I’m wondering if there’s a prop I can use to control auto playing of the video when the screen get mounted and also a way to close the trimming video progress bar when the onFinishing is triggered. Because currently I use the close editor function to close the entire thing I want to just close the modal for the process bar for the trimming video when it’s successfully without having to entirety close the editor

**Comment by maitrungduc1410** [comment]
I'll add support for this

**Comment by maitrungduc1410** [comment]
@benjamin-luupli released, pls upgrade to `2.2.0`

**Comment by benjamin-luupli** [comment]
Great has new props been introduced for this functionality

**Comment by benjamin-luupli** [comment]
Great thanks for the effort
