### ISSUE TITLE
Video trimming dialog got stuck (2.2.0) version and preview is blank for some of android devices when uploaded from gallery.

### ISSUE THREAD

**Issue by stefhivm** [maitrungduc1410/react-native-video-trim#64]
Verision: 2.2.0

**Comment by maitrungduc1410** [comment]
please check onLog event it should tell you what's going on

Preview is blank when you playing?

can you share your input video?

**Comment by stefhivm** [comment]
https://github.com/user-attachments/assets/0ea937a0-10b0-4d9c-afff-e29baefc7a50

**Comment by stefhivm** [comment]
And preview is not showing only when picking from gallery. In addition some of the android device its working fine

**Comment by stefhivm** [comment]
![trim preview](https://github.com/user-attachments/assets/b32456d1-818c-45e6-805d-8c74ebaba155)

**Comment by stefhivm** [comment]
Its my bad. I chose video which is temp file. Sorry !
