### ISSUE TITLE
Not playing from the trim start position when re-playing [Android]

### ISSUE THREAD

**Issue by DejaVuRox** [maitrungduc1410/react-native-video-trim#65]
There seems to be a small issue with the behavior of the play button when you trim the video

Expected behavior (also how it works on the native video editor):
1. trim the video (I put the start time at a new position)
2. play the video till the end
3. press play again, video is played from the trim start time position

Package behavior:
1. same
2. same
3. press play again, playing from the original start of the video and not from the trim start position

Do you think you can provide a fix? 
You did an awesome job on this package!

**Comment by maitrungduc1410** [comment]
Thanks for reporting, I'll check and get back to you

**Comment by maitrungduc1410** [comment]
hey @DejaVuRox on which platform did you face the issue?

**Comment by DejaVuRox** [comment]
it happened on Android but can check it also on IOS

**Comment by maitrungduc1410** [comment]
Can you share me screen recording of the issue ?(for each platform you face the issue)

**Comment by DejaVuRox** [comment]
u can just follow the steps i described and after setting new start time, you let it play till end and just press play again, it will not play from the new start time

**Comment by Vignesh1318** [comment]
Is this any update @maitrungduc1410

**Comment by Vignesh1318** [comment]
Check this below attachment 

Uploading screen-recording-2024-09-24-at-62106-pm_KobXRG4t.mp4…

**Comment by Vignesh1318** [comment]
> @Vignesh1318 i'm busy recently, will setup sometime this week to work on this

Thanks for the update @maitrungduc1410

**Comment by maitrungduc1410** [comment]
hi @Vignesh1318 @DejaVuRox I fixed the issue, please upgrade to 2.2.4

**Comment by Vignesh1318** [comment]
> hi @Vignesh1318 @DejaVuRox I fixed the issue, please upgrade to 2.2.5

Thanks @maitrungduc1410 I'll check and report back to you.

**Comment by Vignesh1318** [comment]
Hi @maitrungduc1410 This issue resolved but i got a another issue

When trimming the video, after I click play, it starts from the original position instead of the trimmed start point.

Please check the attachement

https://github.com/user-attachments/assets/182dd72b-e854-4e0d-abfd-19d68726e7d2

**Comment by maitrungduc1410** [comment]
hi @Vignesh1318 I fixed that play from wrong position issue, please upgrade to 2.2.6

**Comment by Vignesh1318** [comment]
Hi @maitrungduc1410 Yes it's working fine now.

Thanks for the support.

**Comment by Vignesh1318** [comment]
Hi @maitrungduc1410 

Sorry to interrupt, but I’ve found another issue.

On Android, when trimming a video, if I click the play button, it plays the entire video instead of just the trimmed portion selected by the user.

Kindly check the attachment also.


https://github.com/user-attachments/assets/ecef9068-b716-46a5-82f9-8de941bdb255
