### ISSUE TITLE
FFmpeg builds locally but has conflicting names in production

### ISSUE THREAD

**Issue by benjamin-luupli** [maitrungduc1410/react-native-video-trim#66]
Hi package builds alright on my ios device locally when I do pod install with the command you gave
FFMPEGKIT_PACKAGE=https FFMPEGKIT_PACKAGE_VERSION=6.0 pod install
but on app center when I'm trying to build for production I get this error
[!] The 'Pods-app' target has frameworks with conflicting names: ffmpegkit.xcframework, libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.

is there any suggestion to by-pass this in my production environment in appcenter?

**Comment by maitrungduc1410** [comment]
I see few people have faced the same issue, do you have a sample app so that I can have a try on my end?

**Comment by maitrungduc1410** [comment]
are you using some other FFMPEG lib? (like `ffmpeg-kit-react-native`

**Comment by benjamin-luupli** [comment]
Yh I'm using that

**Comment by maitrungduc1410** [comment]
then you have to find exact version that `ffmpeg-kit-react-native` is using

**Comment by maitrungduc1410** [comment]
try this:

ios: add this to your `ios/Podfile`
```
pod 'ffmpeg-kit-react-native', :subspecs => ['https'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'
```

Android: app>build.gradle:
```
ext {
    ffmpegKitPackage = "https"
}
```

**Comment by benjamin-luupli** [comment]
I'm using version 6.0.0, how do I ensure the one your package matches it?

**Comment by maitrungduc1410** [comment]
it's in README: https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#ffmpeg-version

**Comment by benjamin-luupli** [comment]
Okay great will try

**Comment by maitrungduc1410** [comment]
Added instruction how to solve this issue in [README](https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#naming-conflict-with-ffmpeg-kit-react-native)

**Comment by benjamin-luupli** [comment]
![Screenshot 2024-09-02 at 22 39 21](https://github.com/user-attachments/assets/ac89e438-0af9-4ccd-b2a4-90934860fd4d)

i tried again with the laid down method but still refusing to build find attached the screenshort

**Comment by maitrungduc1410** [comment]
> ![Screenshot 2024-09-02 at 22 39 21](https://private-user-images.githubusercontent.com/138477757/363796267-ac89e438-0af9-4ccd-b2a4-90934860fd4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzQzNzUsIm5iZiI6MTcyNzc3NDA3NSwicGF0aCI6Ii8xMzg0Nzc3NTcvMzYzNzk2MjY3LWFjODllNDM4LTBhZjktNGNjZC1iMmE0LTkwOTM0ODYwZmQ0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwOTE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmYwMDIwNmQ0YWQyNmVkZmZhM2JjZGVjNjY3Yzg2YjZmYmUzZTk2NjZmYzJiNTNmZGZhOTgzNDQ5NzFlNDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kaE5iyJDbzooGSRiDL8M-qYz8hARNd6AGQG-ADCLRAA)
> 
> i tried again with the laid down method but still refusing to build find attached the screenshort

you're doing it the wrong way. check my comment: https://github.com/maitrungduc1410/react-native-video-trim/issues/48#issuecomment-2385293382
