### ISSUE TITLE
Trimming Video dialog will on random times hang and when canceling crash app only on Android

### ISSUE THREAD

**Issue by LianVyv** [maitrungduc1410/react-native-video-trim#69]
When I record a video and then call the trim function it will hang on "Trimming Video..." dialog, this does not happen every time it is like 50% working and 50% hanging. Then when it is hanging and I click cancel then it crashes my Android app.

- **Library version**: 2.2.1.
- **Device**: Real device
- **Device details**: Infinix HOT 30 PLAY running on Android XOS 12.6.0
- **minSDKVersion**: 24
- **RN version**: 0.74.1

Steps I took 
1. I recorded a video on my real device
2. Then called the following code with my recorded videos URI
```Javascript
 showEditor(video.uri, {
          maxDuration: 60,
          enableCancelDialog: false,
          enableSaveDialog: false,
          saveButtonText: 'Upload',
});
```

I also tried this code with no options and same issue
```Javascript
 showEditor(data.uri);
```
3. Then when editor shows I clicked save
4. Then clicked proceed
5. Then get stuck on "Trimming Video..." dialog
6. Then click cancel
7. Then click proceed
8. Then the app crashes

iOS works fine only happens for me on Android. 

Here is the full logs when it hangs [logs.txt](https://github.com/user-attachments/files/16832262/logs.txt)

**Comment by LianVyv** [comment]
Here is the LogCat logs from I record the video then open Trim then it hangs and then when I click cancel it crashes

[Logcat.txt](https://github.com/user-attachments/files/16832508/Logcat.txt)

**Comment by maitrungduc1410** [comment]
thanks for reporting, I'll fix the error

**Comment by maitrungduc1410** [comment]
please upgrade to 2.2.2, I fixed the issue

**Comment by LianVyv** [comment]
Hi @maitrungduc1410 

So the crashing has been fixed on 2.2.2 but the actual issue is not fixed. There is 2 issues here

1. Sometimes it still get stuck on trimming
2.When I click cancel the dialog does not disappear it just stays there

Videa I trimmed: https://drive.google.com/file/d/19Nq8wCEooKthAOpC4xesvis6vpqRhRI7/view?usp=sharing
Videa recording of the issue: https://drive.google.com/file/d/1vp4i0IlAzUEJ2fumF07ZvAgu7EwMB9ih/view?usp=sharing

[Logs.txt](https://github.com/user-attachments/files/16920654/Logs.txt)

**Comment by maitrungduc1410** [comment]
can share me your JS code? (how you're calling `showEditor`)

**Comment by LianVyv** [comment]
@maitrungduc1410 

```Javascript
showEditor(data.uri, {
   maxDuration: maxDurationTime,
   enableCancelDialog: false,
   enableSaveDialog: false,
   saveButtonText: 'Upload',
});
````

**Comment by maitrungduc1410** [comment]
@LianVyv what's the value for `maxDurationTime`?

**Comment by LianVyv** [comment]
@maitrungduc1410 see below. Let me know if you need anything else. 

```
const maxDurationTime = 60;
```

The video is local on the device. 

Screen recording: https://drive.google.com/file/d/19RwqZYjeZHVJk7gr405Z9AhaMt-yoI22/view?usp=sharing

I have selected the video and then pass it to showEditor function. The video trimming finishes but the dialog stays there.

**Comment by maitrungduc1410** [comment]
@LianVyv please upgrade to 2.2.3. I fixed the issue

detail: for very short video, the trimming finishes too fast right before opening the progress dialog. Which leads to editor UI is closed, but progress dialog is still there

**Comment by LianVyv** [comment]
@maitrungduc1410 thanks again for your quick fixes. It seems like that did the trick and it works fine now on Android 😁

**Comment by maitrungduc1410** [comment]
Thanks for help me find valuable bugs, it really helps 🙏
