### ISSUE TITLE
Android 11 support request.

### ISSUE THREAD

**Issue by yousafConovo** [maitrungduc1410/react-native-video-trim#7]
This package does not support android 11 at the moment. Event if i remove WRITE_EXTERNAL_STORAGE permission from showEditor function the video is not being saved to device.

**Comment by maitrungduc1410** [comment]
can you elaborate what exactly the issue you're facing?

This `This package does not support android 11 at the moment`, or this `the video is not being saved to device`?

**Comment by maitrungduc1410** [comment]
> I am getting file path on onFinishTrimming but it is not accessible.

what do you mean by "accessible"?

**Comment by yousafConovo** [comment]
In my app there is a user stories feature just like instagram. I need to trim the video if it's above a certain duration and send play that video in react-native-video-player. after trimming the video file and passing the trimmed file path to react-native-video-player i get an error saying that the file is not accessible. But the same code is working perfectly fine on IOS.

**Comment by maitrungduc1410** [comment]
let me check on this and get back to you

**Comment by maitrungduc1410** [comment]
I'm trying to reproduce your scenario but can't reproduce the issue.

- I trimmed a video
- take the file path and pass to `isValidVideo`, it returns `true`
- I can also do another trim for the trimmed video

**Comment by yousafConovo** [comment]
The issue was with video that had a space in their name. I ended up with a work around. I converted the video to base64 and wrote it to my application's folder with a new name that had no space in it and it worked.

**Comment by shiyansiva** [comment]
@yousafConovo  Could you please share a piece of code that you used to solve this issue?
