### ISSUE TITLE
Android release apk getting large size.

### ISSUE THREAD

**Issue by sw-tt-hitendrachavda** [maitrungduc1410/react-native-video-trim#70]
I have used the video trim library for trimming the video when i make the release apk  it apk size getting large. Before installing the package it was small size like 55 mb but when i install the package and check it size getting large 160 mb

Please suggest for the issue.

Thanks

**Comment by maitrungduc1410** [comment]
it depends on which ffmpeg package you're using, `min` gives smallest bundle size

https://github.com/maitrungduc1410/react-native-video-trim?tab=readme-ov-file#customize-ffmpeg-version

**Comment by maitrungduc1410** [comment]
`full` will give larger size.

by default it's `min` already

**Comment by sw-tt-hitendrachavda** [comment]
i have used 
ffmpegKitPackage = "min"
now it's size reduce and it's 120 mb
still it's large size
anything else?

**Comment by maitrungduc1410** [comment]
"min" is the smallest one already

But from 50mb -> 120mb it's huge

I'll verify this and get back to you tmr

**Comment by maitrungduc1410** [comment]
hi @sw-tt-hitendrachavda I tried with fresh new RN project then instal `react-native-video-trim`, without any change `ffmpeg-min` will be used by default

Before: 23.1MB

<img width="762" alt="Screenshot 2024-09-07 at 10 29 22 AM" src="https://github.com/user-attachments/assets/0db8dff6-4fef-4028-841b-3919532ddb70">

After: 51.8MB

<img width="765" alt="Screenshot 2024-09-07 at 10 28 29 AM" src="https://github.com/user-attachments/assets/3e8a6447-0c4b-46ef-8053-5152d5c08d39">
