### ISSUE TITLE
Alart  not close

### ISSUE THREAD

**Issue by Chirag069** [maitrungduc1410/react-native-video-trim#71]
if i am pass saveToPhoto:false Trimming Video...  alart not close
showEditor(uri, {
          type: 'video',
          maxDuration: 30,
          fullScreenModalIOS: true,
          saveToPhoto: false,
          removeAfterSavedToPhoto: false,
          enableHapticFeedback: false,
          cancelButtonText: 'Back',
          saveButtonText: 'Next',
          trimmingText: 'Trimming Video...',
          enableCancelDialog: false,
          enableSaveDialog: false,
          closeWhenFinish: true,
        });

https://github.com/user-attachments/assets/6b049f1c-8f90-4545-a177-bcf802d5e8c3

**Comment by Chirag069** [comment]
saveToPhoto=true select work currect alart close

**Comment by maitrungduc1410** [comment]
thanks for reporting, I'll check it and get back to you soon

**Comment by maitrungduc1410** [comment]
hi which version are you using? note that latest is 2.2.3

**Comment by marcelino-borges** [comment]
I might have the same with version `6.1.0`.
I have to click twice in the "save" button in the trimming modal to close it

**Comment by maitrungduc1410** [comment]
@marcelino-borges can you reproduce again, and tell me exactly how to repo it?

Share me your code as well if possible
