### ISSUE TITLE
FFmpeg builds locally but has conflicting names in production

### ISSUE THREAD

**Issue by benjamin-luupli** [maitrungduc1410/react-native-video-trim#72]
![363796267-ac89e438-0af9-4ccd-b2a4-90934860fd4d](https://github.com/user-attachments/assets/4332050a-832b-4fd8-8ec5-392511ce932e)

attached is the error reproduced after following the instruction in the readme

**Comment by maitrungduc1410** [comment]
I already pinned an issue about this, please check again
