### ISSUE TITLE
arthenica/ffmpeg-kit LTS Support

### ISSUE THREAD

**Issue by terence1990** [maitrungduc1410/react-native-video-trim#73]
Hello!

Wondering if you know of any specific features from Main 6.0.2 release, or since v6.0.LTS, that you are using which makes this incompatible with arthenica/ffmpeg-kit v6.0.LTS

**Comment by maitrungduc1410** [comment]
The only feature I use from the package is simply just cut a video without any other features (encode/decode, crf...)
