### ISSUE TITLE
[ANDROID] isValidFile method always returns false

### ISSUE THREAD

**Issue by ajalasegun1** [maitrungduc1410/react-native-video-trim#77]
On android, the isValidFile method on android returns and object 
`{
  "duration": -1,
  "fileType": "unknown",
  "isValid": false
}`
This is what the path looks like: `file:///storage/emulated/0/Android/data/[package_name]/cache/temp/1728725249271.mp4`

On iOS everything works fine.

I am using the library react-native-image-crop-picker to pick the video file.

**Comment by maitrungduc1410** [comment]
I guess the file is already deleted?

can you inspect it using Android studio?

**Comment by ajalasegun1** [comment]
@maitrungduc1410 thanks for your reply. You are correct. I was cleaning the temporal storage on component unmount. For some reason, it is being triggered before the video trim modal pops up. It works fine now thanks.
