### ISSUE TITLE
Conflicting Issue with ffmpeg-kit-react-native@6.0.2

### ISSUE THREAD

**Issue by dnielgonzlz** [maitrungduc1410/react-native-video-trim#78]
Library does not allow to be installed once I have to run Pod install, since it's conflicting with the current version of ffmpeg-kit-react-native@6.0.2

<img width="1027" alt="Screenshot 2024-10-18 at 8 12 42 PM" src="https://github.com/user-attachments/assets/42705849-71a0-49bf-b522-5d9bc8fb498a">

**Comment by maitrungduc1410** [comment]
have you checked the pinned issue?

also it's there in the bottom of the README

**Comment by maitrungduc1410** [comment]
https://github.com/maitrungduc1410/react-native-video-trim/issues/66

**Comment by dnielgonzlz** [comment]
Tried it, and it didn't work.

It builds the pods OK after the FFMPEGKIT_PACKAGE=full
FFMPEG_KIT_PACKAGE_VERSION=6.0.2 pod install

But then, when I run my npx expo run:ios --device to build the app on my
phone, it gives me the same error and it says that it couldn't install the
CocoaPods.

Thanks for the quick response tho!

**Comment by maitrungduc1410** [comment]
so you're using Expo, not rn cli?

**Comment by dnielgonzlz** [comment]
Yes, I am!

**Comment by maitrungduc1410** [comment]
Can I have your package.json?

**Comment by maitrungduc1410** [comment]
@dnielgonzlz hey I tested with Expo, it worked fine with my solution.

Example error:

<img width="1377" alt="Screenshot 2024-10-23 at 11 58 05 PM" src="https://github.com/user-attachments/assets/52235ca6-67c7-4646-af9b-33eb13ffd55c">

As you can see, it clearly shows that `ffmpeg-kit-react-native` uses `https`, version 6.0

then you just simply run this:
```
FFMPEGKIT_PACKAGE=https FFMPEG_KIT_PACKAGE_VERSION=6.0 pod install
```

Result:

<img width="1360" alt="Screenshot 2024-10-24 at 12 00 45 AM" src="https://github.com/user-attachments/assets/07fd6cf3-4c77-4393-91da-56d081128240">
