### ISSUE TITLE
Modal was closed

### ISSUE THREAD

**Issue by shiyansiva** [maitrungduc1410/react-native-video-trim#8]
I encountered an issue When I open the **showmodal** from one modal page and then proceed to trim the video within the trimmer modal, both the trimmer modal and our existing modal page close simultaneously.

**Comment by shiyansiva** [comment]
@maitrungduc1410  "Both modals refer to our existing modal page and the trimmer page. In our current setup, we have one modal page, and when we open the trimmer page from that modal, if I trim the video on the trimmer page, it automatically closes both the trimmer page and the parent page."

**Comment by maitrungduc1410** [comment]
okay, I'll check this and get back to you

**Comment by shiyansiva** [comment]
Iphone 12

**Comment by maitrungduc1410** [comment]
hi @shiyansiva  I fixed this issue, pls upgrade to `1.0.4`

**Comment by shiyansiva** [comment]
@maitrungduc1410 Your help is greatly valued. The problem has been resolved, and everything is running smoothly as anticipated. 🙌

**Comment by sanketappsimity** [comment]
> @maitrungduc1410 Your help is greatly valued. The problem has been resolved, and everything is running smoothly as anticipated. 🙌

Can you pls share a peace of code like how you are handling in ios as well as android 
cause in ios i am getting (File is not Valid) while i am passing url  
so can you pls Past here how you are passing Url in ios from gallery like ios url path 
it would be really help full 

thanks

**Comment by maitrungduc1410** [comment]
Hi @sanketappsimity `isValidVideo` is used for local file only, at the moment you can't use it for remote file, I was considering to implement it, but if we do that then it'll need to download the file and do validation, and it seems too overhead.


You can check example app to see how I did in my local: https://github.com/maitrungduc1410/react-native-video-trim/tree/master/example

**Comment by shiyansiva** [comment]
> > @maitrungduc1410 Your help is greatly valued. The problem has been resolved, and everything is running smoothly as anticipated. 🙌
> 
> Can you pls share a peace of code like how you are handling in ios as well as android cause in ios i am getting (File is not Valid) while i am passing url so can you pls Past here how you are passing Url in ios from gallery like ios url path it would be really help full
> 
> thanks

Sure @sanketappsimity, Could you please attempt this on a real device? I encountered the same issue when using the simulator.
