### ISSUE TITLE
Trimming Process Does Not Generate Expected Video, Sometime Trimmer Modal Stays Open

### ISSUE THREAD

**Issue by shiyansiva** [maitrungduc1410/react-native-video-trim#9]
After using the trimming functionality, we've encountered several issues on Android devices.

**Expected Behavior:**
After trimming, the application should generate the trimmed video as expected. The trimmer modal should close promptly when users click "Save" or "Cancel,"

**Actual Behavior:**
Currently, the application is not generating the trimmed video as expected. It may be missing or not reflecting the intended edits. Sometimes, the trimmer modal does not close as expected. It remains open even after the user clicks the "proceed" button.

**Environment:**
Android 13 (Real Device)
Also tested on Android 11 and 12 with Emulator.

**Additional Information:**
"react": "16.13.1"
"react-native": "~0.63.4",
"react-native-video-trim": "^1.0.4",

 buildToolsVersion = "30.0.2"
 minSdkVersion = 21
 compileSdkVersion = 30
 targetSdkVersion = 33
 kotlinVersion = '1.3.41'

**Comment by shiyansiva** [comment]
@maitrungduc1410 have you encountered this issue?

**Comment by maitrungduc1410** [comment]
Can you listen for `onError` to see if any error is there?

**Comment by shiyansiva** [comment]
@maitrungduc1410 I'm not receiving any error messages. After examining the console, it seems that the event emitter wasn't triggered. My device is writing a zero-size file.

**Comment by maitrungduc1410** [comment]
hi @shiyansiva  is this issue still happening?

If yes, is it possible for you to prepare a test repo with same dependencies so that I can try to reproduce?

**Comment by shiyansiva** [comment]
Hello, @maitrungduc1410. Yes, the issue still persists. I attempted to create a test repository with the same dependencies, but I encountered errors due to the extensive configuration in our project.

**Comment by shiyansiva** [comment]
@maitrungduc1410 Can you use this [repo](https://github.com/shiyansiva/example)

**Comment by maitrungduc1410** [comment]
thanks @shiyansiva , I'll check

**Comment by shiyansiva** [comment]
> thanks @shiyansiva , I'll check

@maitrungduc1410  Have you had time to check this repo

**Comment by maitrungduc1410** [comment]
Hi, 

i've been trying to run your project, but keeps on facing issues:
- pod install failed
<img width="1260" alt="Screenshot 2023-09-23 at 12 30 45 AM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/16630193/83dbab7a-3e00-44a7-937a-b2d3d8aed78a">

- `run-android` failed:

<img width="1084" alt="Screenshot 2023-09-23 at 12 31 09 AM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/16630193/e19a1435-5e9f-4400-bccc-d5dbab97f0d3">

- I try to fix issue with android but it came with another issue


Can you help me do this:
- with your own project, the real one, try to run one more time on Android with Real device
- Open Android studio and make sure you can see your device there. Open Logcat and select your device to view its log
- `run-android`, and when you hit `Proceed`, pay attention closely to Logcat at the time the issue happens. Then send me your insights

**Comment by shiyansiva** [comment]
> Hi,
> 
> i've been trying to run your project, but keeps on facing issues:
> 
> * pod install failed
> 
> <img alt="Screenshot 2023-09-23 at 12 30 45 AM" width="1260" src="https://user-images.githubusercontent.com/16630193/269999254-83dbab7a-3e00-44a7-937a-b2d3d8aed78a.png">
> * `run-android` failed:
> 
> <img alt="Screenshot 2023-09-23 at 12 31 09 AM" width="1084" src="https://user-images.githubusercontent.com/16630193/269999373-e19a1435-5e9f-4400-bccc-d5dbab97f0d3.png">
> * I try to fix issue with android but it came with another issue
> 
> Can you help me do this:
> 
> * with your own project, the real one, try to run one more time on Android with Real device
> * Open Android studio and make sure you can see your device there. Open Logcat and select your device to view its log
> * `run-android`, and when you hit `Proceed`, pay attention closely to Logcat at the time the issue happens. Then send me your insights

I haven't checked with iOS only run the Android with below commands

-> yarn install
->npx react-native run-android

**Comment by shiyansiva** [comment]
Hi @maitrungduc1410,  After removing the yarn.lock file, I attempted to reinstall dependencies using **yarn install** and run the Android project with **npx react-native run-android**. Unfortunately, this resulted in an error. However, I managed to resolve the issue by creating a local.properties file within the Android folder and adding the following line, which points to the correct SDK path **sdk.dir=/Users/sivakumar.m/Libr
ary/Android/sdk**. After making this adjustment, the project ran successfully. Please give it a try, and let me know if this solution works for you as well.

![image](https://github.com/maitrungduc1410/r
![image (1)](https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/51394274-82d2-4a93-8bb5-87a3b917fbd9)
eact-native-video-trim/assets/35214422/8fb21897-8068-4a03-8b21-7345406cf03a)

**Comment by shiyansiva** [comment]
@maitrungduc1410 Have you encountered this build issue recently

**Comment by maitrungduc1410** [comment]
Hi @shiyansiva today,I'll try deleting package-lock and see if it works

**Comment by shiyansiva** [comment]
> Hi @shiyansiva today,I'll try deleting package-lock and see if it works

Thanks @maitrungduc1410

**Comment by maitrungduc1410** [comment]
Hi @shiyansiva it's still throwing issue when `run-android`

<img width="1269" alt="Screenshot 2023-09-26 at 10 13 50 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/16630193/52741576-4b9e-4d76-8708-1b2953f8b8bf">

**Comment by maitrungduc1410** [comment]
I think you just run your project on your machine and help me do this:

with your own project, the real one, try to run one more time on Android with Real device
Open Android studio and make sure you can see your device there. Open Logcat and select your device to view its log
run-android, and when you hit Proceed, pay attention closely to Logcat at the time the issue happens. Then send me your insights

**Comment by shiyansiva** [comment]
@maitrungduc1410 Can you please check this
<img width="1703" alt="Screenshot 2023-09-26 at 8 38 38 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/d8d5cdc9-0d5e-4292-8b44-d7d472dcfce8">
<img width="1728" alt="Screenshot 2023-09-26 at 8 38 56 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/99f100fe-5716-403b-a15d-1be91cf18971">
<img width="1723" alt="Screenshot 2023-09-26 at 8 42 09 PM" src="https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/63e3437e-2e45-410e-81c2-4b04ca868aef">

**Comment by maitrungduc1410** [comment]
The above log showed with the issue? (Modal not closed issue?)

**Comment by shiyansiva** [comment]
> The above log showed with the issue? (Modal not closed issue?)

No, the modal is closed now, but unfortunately, the Trimming Process did not generate the expected trimmed video

**Comment by maitrungduc1410** [comment]
Hi @shiyansiva please upgrade to v1.0.6 and try again

**Comment by shiyansiva** [comment]
> Hi @shiyansiva please upgrade to `^1.0.8` and try again

@maitrungduc1410 Thank you for your reply. I've verified with the latest versions(1.0.8 & 1.0.10), but unfortunately, I'm still encountering the same issue.

**Comment by maitrungduc1410** [comment]
Hi @shiyansiva you mean the build issue right?

Since I couldn't reproduce your issue, it's very hard to tell.

I think it's high chance because of your project config, project dependencies...

You can try with new project and see if it works

**Comment by shiyansiva** [comment]
> Hi @shiyansiva you mean the build issue right?
> 
> Since I couldn't reproduce your issue, it's very hard to tell.
> 
> I think it's high chance because of your project config, project dependencies...
> 
> You can try with new project and see if it works

@maitrungduc1410 No , the Trimming Process did not generate the expected trimmed video (facing the issue only is android)

**Comment by maitrungduc1410** [comment]
Is it possible for you to provide a sample video?

Also your code?

**Comment by shiyansiva** [comment]
@maitrungduc1410 Please check this video
https://github.com/maitrungduc1410/react-native-video-trim/assets/35214422/e4b1acf2-a8d0-4519-9967-032b0c75a394
